{
  "formatVersion": "1.1",
  "component": {
    "group": "com.abdelaziz_mahdy.pytorch_lite",
    "module": "pytorch_lite_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        }
      ],
      "files": [
        {
          "name": "pytorch_lite_profile-1.0.aar",
          "url": "pytorch_lite_profile-1.0.aar",
          "size": 34341,
          "sha512": "4127e002b188d939addff215451cf0114e46702e366d92a99a8729ffafdf29f797b9f7e8a6dfa0f9beb097ce1bd6c10e413c71bb16e59c846c0772f3e3039b38",
          "sha256": "105dbca090cf35ce4ebf831861aa70d1c37a91f95caef0d88d72ea77eeee067b",
          "sha1": "94b51687aea386164943efe872baddc0b5006105",
          "md5": "0c8a7d3dc37e8e56c49204f8c4263d63"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        },
        {
          "group": "org.pytorch",
          "module": "pytorch_android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.pytorch",
          "module": "pytorch_android_torchvision",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "nativeloader",
          "version": {
            "requires": "0.10.5"
          }
        }
      ],
      "files": [
        {
          "name": "pytorch_lite_profile-1.0.aar",
          "url": "pytorch_lite_profile-1.0.aar",
          "size": 34341,
          "sha512": "4127e002b188d939addff215451cf0114e46702e366d92a99a8729ffafdf29f797b9f7e8a6dfa0f9beb097ce1bd6c10e413c71bb16e59c846c0772f3e3039b38",
          "sha256": "105dbca090cf35ce4ebf831861aa70d1c37a91f95caef0d88d72ea77eeee067b",
          "sha1": "94b51687aea386164943efe872baddc0b5006105",
          "md5": "0c8a7d3dc37e8e56c49204f8c4263d63"
        }
      ]
    }
  ]
}
