{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 73534,
          "sha512": "547f33bd4902b0c6d3fdfba1d696244b9405846b6768ce9861127ffb25710f8b8b0e4ecf68ab36ca6e3084a67de0b1f7d286a6f87c04354d4003bf36163fe84b",
          "sha256": "a183f815b945f923c567dfd34331285299ca8f521a165cafc87ac55cecb9426e",
          "sha1": "5b66c692c5adc6c7a847a881af0c42e029b6476c",
          "md5": "736b991e6af7651b04a57e53795cd458"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 73534,
          "sha512": "547f33bd4902b0c6d3fdfba1d696244b9405846b6768ce9861127ffb25710f8b8b0e4ecf68ab36ca6e3084a67de0b1f7d286a6f87c04354d4003bf36163fe84b",
          "sha256": "a183f815b945f923c567dfd34331285299ca8f521a165cafc87ac55cecb9426e",
          "sha1": "5b66c692c5adc6c7a847a881af0c42e029b6476c",
          "md5": "736b991e6af7651b04a57e53795cd458"
        }
      ]
    }
  ]
}
