{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-1.0.aar",
          "url": "camera_android_profile-1.0.aar",
          "size": 122493,
          "sha512": "8dd39c1bd2ef269a0e1320345a2efe2ee6a85948a4889ea10bfa49850dee3cb992049e34b99fa1553d447a3832563dc374d97b15f9eed93a5740e674e3f5f5ce",
          "sha256": "8afa9d6289f7874d077d12b82f4b19167cf2d9701e1b2bb8db064c74b512dc26",
          "sha1": "d078c181ed1591d6632a400aa39e27625cccebb5",
          "md5": "4d869e2d914a2aea7e1c8bee50292d71"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_profile-1.0.aar",
          "url": "camera_android_profile-1.0.aar",
          "size": 122493,
          "sha512": "8dd39c1bd2ef269a0e1320345a2efe2ee6a85948a4889ea10bfa49850dee3cb992049e34b99fa1553d447a3832563dc374d97b15f9eed93a5740e674e3f5f5ce",
          "sha256": "8afa9d6289f7874d077d12b82f4b19167cf2d9701e1b2bb8db064c74b512dc26",
          "sha1": "d078c181ed1591d6632a400aa39e27625cccebb5",
          "md5": "4d869e2d914a2aea7e1c8bee50292d71"
        }
      ]
    }
  ]
}
