{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 69811,
          "sha512": "a1fa804b5492c2949be2899234693827b2abc0e44a57a2e8397bb2fb563d0f27266f42c116549d8603feaa0ce727b9e2793c29f7c267d10cdae1eb968c5ae8e6",
          "sha256": "bcf42270918689effd9b6361fbb4fb27566f0bebe2be31353147dd4b747e5088",
          "sha1": "ddbc0d304f6f57b04fcae387b7ba88b19d86e213",
          "md5": "9e2994fbd43af61e6cf80a5241540369"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 69811,
          "sha512": "a1fa804b5492c2949be2899234693827b2abc0e44a57a2e8397bb2fb563d0f27266f42c116549d8603feaa0ce727b9e2793c29f7c267d10cdae1eb968c5ae8e6",
          "sha256": "bcf42270918689effd9b6361fbb4fb27566f0bebe2be31353147dd4b747e5088",
          "sha1": "ddbc0d304f6f57b04fcae387b7ba88b19d86e213",
          "md5": "9e2994fbd43af61e6cf80a5241540369"
        }
      ]
    }
  ]
}
