{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12437,
          "sha512": "8c79b48dbf26b54d1d8a8cd148c217fb1ccbfb64ea8a6a2d598f3b302381f60b92ec52a9c63163770dfcd7b3dc18c21e90aa644ed0a2a08b57a43aecc6559dd0",
          "sha256": "b05728895c2368a04a9b0eaefc0a12d7c0de93860dacd6c98cd713307abed80e",
          "sha1": "66a71c732370afee57ad318fadc587dabc90b967",
          "md5": "9449787d92b0f5c4633b2caae45dddfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a86e74cf06f7a7f5f3a52a9d6c1e8f62ef1253dc"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12437,
          "sha512": "8c79b48dbf26b54d1d8a8cd148c217fb1ccbfb64ea8a6a2d598f3b302381f60b92ec52a9c63163770dfcd7b3dc18c21e90aa644ed0a2a08b57a43aecc6559dd0",
          "sha256": "b05728895c2368a04a9b0eaefc0a12d7c0de93860dacd6c98cd713307abed80e",
          "sha1": "66a71c732370afee57ad318fadc587dabc90b967",
          "md5": "9449787d92b0f5c4633b2caae45dddfb"
        }
      ]
    }
  ]
}
